spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:screening;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hanati.bank.screening.entity
